entity_form:
    resource: "@EntityFormBundle/Resources/config/routing.yml"
    prefix:   /

zyrim_entity_form:
    resource: "@ZyrimEntityFormBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
